name: Static Site Auto-Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pages: write
  contents: read
  id-token: write

concurrency:
  group: deploy-pages
  cancel-in-progress: true

jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.publish.outputs.page_url }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Archive site files
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./"

      - name: Publish to GitHub Pages
        id: publish
        uses: actions/deploy-pages@v4
